New Wait for more than one port
Wait code extended

diff --git a/wait b/wait
--- a/wait
+++ b/wait
@@ -1,16 +1,49 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-host=$(env | grep _TCP_ADDR | cut -d = -f 2)
-port=$(env | grep _TCP_PORT | cut -d = -f 2)
+timeout=${TIMEOUT:-30}
 
-echo -n "waiting for TCP connection to $host:$port..."
+# our target format is a newline-delimited list where each item is "host:ip"
+if [ -z "$TARGETS" ]; then
+  # empty TARGETS variable will default to checking all host/ports exposed
+  uris=$(env | grep _TCP= | cut -d= -f2 | cut -c7- )
 
-while ! nc -w 1 $host $port 2>/dev/null
+  if [ $(echo $uris | wc -w) -lt 1 ]; then
+    echo "The linked container(s) export no ports and you didn't specify any manual targets. Exiting" >&2
+    exit 1
+  fi
+else
+  uris=$(echo $TARGETS | sed -e 's/,/ /g' -e 's/\s+/\n/g' | uniq)
+fi
+
+# wait for each target
+if [ -z "$uris" ]; then
+  echo "No wait targets found. Exiting" >&2
+  exit 1
+fi
+
+for uri in $uris
 do
-  echo -n .
-  sleep 1
-done
+  host=$(echo $uri | cut -d: -f1)
+  port=$(echo $uri | cut -d: -f2)
+  [ -n "${host}" ]
+  [ -n "${port}" ]
+  echo -n "Waiting for ${uri}  ."
+  seconds=0
+  while [ "$seconds" -lt "$timeout" ] && ! nc -w 1 $host $port
+  do
+    echo -n .
+    seconds=$((seconds+1))
+    sleep 1
+  done
 
-echo 'ok'
+  if [ "$seconds" -lt "$timeout" ]; then
+    echo "  up!"
+  else
+    echo "  ERROR: unable to connect" >&2
+    exit 1
+  fi
+done
+echo "Everything is up"
+exit 0
